module.exports = [
    {
        id: 0,
        email: 'aaa@aaa',
        password: 'aaa',
        nickname: 'john',
        profile_image: 1,
        room_id: null,
    },
    {
        id: 0,
        email: 'bbb@bbb',
        password: 'bbb',
        nickname: 'hoho',
        profile_image: 2,
        room_id: null,
    },
    {
        id: 0,
        email: 'ccc@ccc',
        password: 'ccc',
        nickname: 'yuri',
        profile_image: 1,
        room_id: null,
    },
    {
        id: 0,
        email: 'ddd@ddd',
        password: 'ddd',
        nickname: 'hoya',
        profile_image: 3,
        room_id: null,
    },
    {
        id: 0,
        email: 'eee@eee',
        password: 'eee',
        nickname: 'anne',
        profile_image: 4,
        room_id: null,
    },
];
